version: '3'
services:
    rundeck:
        container_name: rundeck
        build:
          context: rundeck
          args:
            RUNDECK_IMAGE: ${RUNDECK_IMAGE:-rundeckpro/enterprise:SNAPSHOT}
        links:
          - mysql
        environment:
            RUNDECK_GRAILS_URL: http://localhost:4440
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
            RUNDECK_SECURITY_DBLOGIN_ENABLED: 'true'
            RUNDECK_SECURITY_DBLOGIN_CREATEADMINUSERANDROLES: 'true'
            RUNDECK_SECURITY_DBLOGIN_ADMINUSERNAME: admin
            RUNDECK_SECURITY_DBLOGIN_ADMINPASSWORD: admin
            RUNDECK_PLUGIN_CLUSTER_REMOTEEXECUTION_ENABLED: 'false'
            RUNDECK_FEATURE_ENTERPRISEACL_ENABLED: 'false'
            RUNDECK_FEATURE_ENTERPRISEACLTRANSFER_ENABLED: 'false'
            RUNDECK_SERVER_ADDRESS: 0.0.0.0
            # GCP
            RUNDECK_GCP_PROJECTID: ${GCP_PROJECTID}
            RUNDECK_GCP_ZONE: ${GCP_ZONE}
            RUNDECK_GCP_KEYPATH: keys/project/gcp-demo/gcp-access-key.json
            # AWS
            RUNDECK_AWS_ACCESSKEY: ${AWS_ACCESS_KEY}
            RUNDECK_AWS_SECRETKEY_PATH: keys/project/aws-demo/secret.key
            RUNDECK_AWS_REGION: ${AWS_REGION}
            # ORACLE
            RUNDECK_OCI_TENANTID: ${OCI_TENANTID}
            RUNDECK_OCI_USERID: ${OCI_USERID}
            RUNDECK_OCI_FINGERPRINT: ${OCI_FINGERPRINT}
            RUNDECK_OCI_KEYPATH: keys/project/oracle-cloud-demo/connection.pem
            RUNDECK_OCI_REGION: ${OCI_REGION}
            # Azure
            RUNDECK_AZURE_TENANTID: ${AZURE_TENANTID}
            RUNDECK_AZURE_KEYPATH: keys/project/azure-demo/azure.key
            RUNDECK_AZURE_SUBSCRIPTIONID: ${AZURE_SUBSCRIPTIONID}
            RUNDECK_AZURE_CLIENTID: ${AZURE_CLIENTID}
        ports:
          - 4440:4440
        volumes:
          - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
    mysql:
        container_name: mysql
        image: mysql:8
        expose:
          - 3306
        cap_add:
          - SYS_NICE  # CAP_SYS_NICE reduces error messages in console
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
    client:
      container_name: client
      build:
        context: client
      environment:
        CONFIG_FILE: import.yml
        RUNDECK_URL: http://rundeck:4440
        RUNDECK_API_URL: http://localhost:4440
        RUNDECK_TOKEN: u5gJoKU3NpS6IC4lFmPQFfDkUlZnQOXp
        # AZURE
        AZURE_API_KEY: ${AZURE_API_KEY}
        AZURE_TENANTID: ${AZURE_TENANTID}
        AZURE_SUBSCRIPTIONID: ${AZURE_SUBSCRIPTIONID}
        AZURE_CLIENTID: ${AZURE_CLIENTID}
        # GCP
        GCP_PROJECTID: ${GCP_PROJECTID}
        GCP_ZONE: ${GCP_ZONE}
        GCP_KEY_PATH: ${GCP_KEY_PATH}
        # AWS
        AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
        AWS_SECRET_KEY: ${AWS_SECRET_KEY}
        AWS_REGION: ${AWS_REGION}
        # ORACLE
        OCI_TENANTID: ${OCI_TENANTID}
        OCI_USERID: ${OCI_USERID}
        OCI_FINGERPRINT: ${OCI_FINGERPRINT}
        OCI_REGION: ${OCI_REGION}
        OCI_KEY_PATH: ${OCI_KEY_PATH}
      volumes:
        - ./data/linux_id_rsa:/rundeck-cli/data/linux_id_rsa
        - ./${GCP_KEY_PATH}:/rundeck-cli/data/gcp-access-key.json
        - ./${OCI_KEY_PATH}:/rundeck-cli/data/oracle-connection.pem
    node:
      container_name: node1
      image: rundeck/node-demo
      ports:
         - "22"
      environment:
        - SSHD_PORT=22
      volumes:
        - ./data/linux_id_rsa:/configuration/id_rsa
        - ./data/linux_id_rsa.pub:/configuration/id_rsa.pub
    node2:
      container_name: node2
      image: rundeck/node-demo
      ports:
         - "22"
      environment:
        - SSHD_PORT=22
      volumes:
        - ./data/linux_id_rsa:/configuration/id_rsa
        - ./data/linux_id_rsa.pub:/configuration/id_rsa.pub
